# Written by Ben Pearson
# V0.0.3

"""
This module implements the modules funcitonal_iteration and newton.
"""

# Modules
import constants as c
import functions as f
import newton
import functional_iteration
import pandas as pd


def print_arrs(f_arr, n_arr):
    """Print the arrays generated by functional iteration and newton's method and show the delta"""
    print("\tFuncitonal Iteration\tNewton's Method\tDifference")
    for i in range(c.N):
        if c.N > 100:
            if i % 20 == 0:
                print(
                    str(i)
                    + "\tx =\t"
                    + str(f_arr[i])
                    + ",\tx =\t"
                    + str(n_arr[i])
                    + ",\tdelta =\t"
                    + str(f_arr[i] - n_arr[i])
                )
        else:
            print(
                "x =\t"
                + str(f_arr[i])
                + ",\tx =\t"
                + str(n_arr[i])
                + ",\tdelta =\t"
                + str(f_arr[i] - n_arr[i])
            )


x = 3
data = {
    "f_test": functional_iteration.itor(f.f_test, x),
    "n_test": newton.itor(f.n_test, f.d_n_test, x),
    "f_even": functional_iteration.itor(f.f_even, x),
    "n_even": newton.itor(f.n_even, f.d_n_even, x),
    "f_odd": functional_iteration.itor(f.f_odd, x),
    "n_odd": newton.itor(f.n_odd, f.d_n_odd, x),
}
print_arrs(data["f_test"], data["n_test"])
print_arrs(data["f_even"], data["n_even"])
print_arrs(data["f_odd"], data["n_odd"])

df = pd.DataFrame(data)
df.to_csv("./data.csv")
